
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zerotus
 */
public class DatHang_page1 extends javax.swing.JFrame {

    /**
     * Creates new form DatHang_page1
     */
    public DatHang_page1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TableDoiTac = new javax.swing.JTable();
        btnChooseDT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnDonHang = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TableSanPham = new javax.swing.JTable();
        txtSearchDTBar = new javax.swing.JTextField();
        btnSearchDT = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtSearchSPBar = new javax.swing.JTextField();
        btnSearchSP = new javax.swing.JButton();
        btnChooseSP = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã đơn hàng", "Tên khách hàng", "Địa chỉ giao", "Phí vận chuyển", "Hình thức thanh toán", "Tình trạng đơn hàng", "Chọn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableDoiTac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã đối tác", "Tên đối tác", "Địa chỉ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(TableDoiTac);

        jPanel6.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1240, 230));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 250));

        btnChooseDT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnChooseDT.setText("Chọn đối tác");
        btnChooseDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseDTActionPerformed(evt);
            }
        });
        jPanel3.add(btnChooseDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 100, 150, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 1520, 260));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("HỆ THỐNG ĐẶT VÀ CHUYỂN HÀNG ONLINE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1520, 90));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel7.setText("Danh sách sản phẩm");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, 50));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnBack.setText("Quay lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 720, 140, 40));

        btnDonHang.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnDonHang.setText("Đặt hàng");
        btnDonHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonHangActionPerformed(evt);
            }
        });
        jPanel1.add(btnDonHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 720, 150, 40));

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Chi nhánh", "Số lượng", "Giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(TableSanPham);
        if (TableSanPham.getColumnModel().getColumnCount() > 0) {
            TableSanPham.getColumnModel().getColumn(3).setHeaderValue("Số lượng");
            TableSanPham.getColumnModel().getColumn(4).setHeaderValue("Thành tiền");
        }

        jPanel7.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1240, 240));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1260, 260));

        txtSearchDTBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchDTBarActionPerformed(evt);
            }
        });
        jPanel1.add(txtSearchDTBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 110, 230, 30));

        btnSearchDT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSearchDT.setText("Tìm kiếm");
        btnSearchDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchDTActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearchDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 110, -1, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel8.setText("Danh sách đối tác");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 97, -1, 50));

        txtSearchSPBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchSPBarActionPerformed(evt);
            }
        });
        jPanel1.add(txtSearchSPBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 410, 230, 30));

        btnSearchSP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSearchSP.setText("Tìm kiếm");
        btnSearchSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchSPActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearchSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 410, -1, 30));

        btnChooseSP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnChooseSP.setText("Chọn đối tác");
        btnChooseSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseSPActionPerformed(evt);
            }
        });
        jPanel1.add(btnChooseSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 560, 150, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1540, 780));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChooseSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChooseSPActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtSearchDTBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchDTBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchDTBarActionPerformed

    private void btnDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDonHangActionPerformed

    private void btnSearchDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchDTActionPerformed

    private void txtSearchSPBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchSPBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchSPBarActionPerformed

    private void btnSearchSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchSPActionPerformed

    private void btnChooseDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChooseDTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatHang_page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatHang_page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatHang_page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatHang_page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatHang_page1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableDoiTac;
    private javax.swing.JTable TableSanPham;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnChooseDT;
    private javax.swing.JButton btnChooseSP;
    private javax.swing.JButton btnDonHang;
    private javax.swing.JButton btnSearchDT;
    private javax.swing.JButton btnSearchSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtSearchDTBar;
    private javax.swing.JTextField txtSearchSPBar;
    // End of variables declaration//GEN-END:variables
}
