
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zerotus
 */
public class XuLyDonHang extends javax.swing.JFrame {

    /**
     * Creates new form XuLyDonHang
     */
    public XuLyDonHang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtMaTaiXe = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNumberPhone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtKhuVucHoatDong = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TableDonHang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnXacNhan = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        selectbtnGiaoHangKhongThanhCong = new javax.swing.JRadioButton();
        selectbtnDangGiao = new javax.swing.JRadioButton();
        selectbtnGiaoHangThanhCong = new javax.swing.JRadioButton();
        txtLiDo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã đơn hàng", "Tên khách hàng", "Địa chỉ giao", "Phí vận chuyển", "Hình thức thanh toán", "Tình trạng đơn hàng", "Chọn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Mã tài xế");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, -1));

        txtMaTaiXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaTaiXeActionPerformed(evt);
            }
        });
        jPanel3.add(txtMaTaiXe, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 160, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Số điện thoại");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 130, -1));

        txtNumberPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberPhoneActionPerformed(evt);
            }
        });
        jPanel3.add(txtNumberPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 160, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Số điện thoại");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 130, -1));

        txtKhuVucHoatDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKhuVucHoatDongActionPerformed(evt);
            }
        });
        jPanel3.add(txtKhuVucHoatDong, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, 160, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Khu vực hoạt động");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 200, -1));

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableDonHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã đơn hàng", "Tên khách hàng", "Địa chỉ giao", "Phí vận chuyển", "Hình thức thanh toán", "Tình trạng đơn hàng", "Chọn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(TableDonHang);
        if (TableDonHang.getColumnModel().getColumnCount() > 0) {
            TableDonHang.getColumnModel().getColumn(3).setHeaderValue("Phí vận chuyển");
            TableDonHang.getColumnModel().getColumn(4).setHeaderValue("Hình thức thanh toán");
            TableDonHang.getColumnModel().getColumn(5).setHeaderValue("Tình trạng đơn hàng");
            TableDonHang.getColumnModel().getColumn(6).setHeaderValue("Chọn");
        }

        jPanel6.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1500, 290));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1520, 310));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 1520, 390));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("HỆ THỐNG ĐẶT VÀ CHUYỂN HÀNG ONLINE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1520, 90));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel7.setText("Khu vực hoạt động");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        btnXacNhan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });
        jPanel1.add(btnXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 710, 180, 50));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnBack.setText("Quay lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 710, 170, 50));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("Lí do:");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 60, -1));

        selectbtnGiaoHangKhongThanhCong.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        selectbtnGiaoHangKhongThanhCong.setText("Giao Hàng Không Thành Công");
        selectbtnGiaoHangKhongThanhCong.setIconTextGap(10);
        selectbtnGiaoHangKhongThanhCong.setPreferredSize(new java.awt.Dimension(200, 50));
        selectbtnGiaoHangKhongThanhCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectbtnGiaoHangKhongThanhCongActionPerformed(evt);
            }
        });
        jPanel5.add(selectbtnGiaoHangKhongThanhCong, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 300, 50));

        selectbtnDangGiao.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        selectbtnDangGiao.setText("Đang Giao");
        selectbtnDangGiao.setIconTextGap(10);
        selectbtnDangGiao.setInheritsPopupMenu(true);
        selectbtnDangGiao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectbtnDangGiaoActionPerformed(evt);
            }
        });
        jPanel5.add(selectbtnDangGiao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 120, 30));

        selectbtnGiaoHangThanhCong.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        selectbtnGiaoHangThanhCong.setText("Giao Hàng Thành Công");
        selectbtnGiaoHangThanhCong.setIconTextGap(10);
        selectbtnGiaoHangThanhCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectbtnGiaoHangThanhCongActionPerformed(evt);
            }
        });
        jPanel5.add(selectbtnGiaoHangThanhCong, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 50));
        jPanel5.add(txtLiDo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 390, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel12.setText("Tình trạng đơn hàng");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 250, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 850, 180));
        jPanel5.getAccessibleContext().setAccessibleParent(jLabel9);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1540, 780));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtKhuVucHoatDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKhuVucHoatDongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKhuVucHoatDongActionPerformed

    private void txtNumberPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumberPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumberPhoneActionPerformed

    private void txtMaTaiXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaTaiXeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaTaiXeActionPerformed

    private void selectbtnGiaoHangKhongThanhCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectbtnGiaoHangKhongThanhCongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectbtnGiaoHangKhongThanhCongActionPerformed

    private void selectbtnDangGiaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectbtnDangGiaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectbtnDangGiaoActionPerformed

    private void selectbtnGiaoHangThanhCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectbtnGiaoHangThanhCongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectbtnGiaoHangThanhCongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XuLyDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XuLyDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XuLyDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XuLyDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XuLyDonHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableDonHang;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JRadioButton selectbtnDangGiao;
    private javax.swing.JRadioButton selectbtnGiaoHangKhongThanhCong;
    private javax.swing.JRadioButton selectbtnGiaoHangThanhCong;
    private javax.swing.JTextField txtKhuVucHoatDong;
    private javax.swing.JTextField txtLiDo;
    private javax.swing.JTextField txtMaTaiXe;
    private javax.swing.JTextField txtNumberPhone;
    // End of variables declaration//GEN-END:variables
}
