--XY LY DON HANG

-- DROP PROC SP_CAPNHATTHONGTINNHANVIEN
				
CREATE PROC SP_CAPNHATTHONGTINNHANVIEN
	@MATK CHAR(10),
	@MATKHAU VARCHAR(16),
	@TINHTRANG INT,
	@RESULT NVARCHAR(2000) OUTPUT
AS
SET TRAN ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN
	IF NOT EXISTS(SELECT * 
					FROM TAIKHOAN
					WHERE MATK = @MATK)
	BEGIN
		SET @RESULT = N'Tài khoản không tồn tại'
		--RAISERROR(N'Tài khoản không tồn tại', 16, 1)
		RETURN
	END

	WAITFOR DELAY '0:0:05'

	BEGIN TRY
		IF (@MATK = '') 
		BEGIN
			UPDATE TAIKHOAN
			SET TINHTRANG = @TINHTRANG
			WHERE MATK = @MATK
		END
		ELSE
		BEGIN
			UPDATE TAIKHOAN 
			SET MATKHAU = @MATKHAU, TINHTRANG = @TINHTRANG
			WHERE MATK = @MATK
		END
	END TRY
	BEGIN CATCH 
		DECLARE @ErrorMsg VARCHAR(2000)
		SELECT @ErrorMsg = N'Lỗi: ' + ERROR_MESSAGE()
		SET @RESULT = N'Lỗi: ' + ERROR_MESSAGE()
		--RAISERROR(@ErrorMsg, 16,1)
		ROLLBACK TRAN
		RETURN
	END CATCH
	SET @RESULT = N'Cập nhật thành công'
COMMIT TRAN
RETURN

GO