--XY LY DON HANG

--DROP PROC SP_XULYDH
				
CREATE 
--ALTER
PROC SP_XULYDH
	@MATX CHAR(10),
	@MADH CHAR(10),
	@TINHTRANG INT

AS
BEGIN TRAN
	SET TRAN ISOLATION LEVEL SERIALIZABLE
	DECLARE @TINHTRANGDH INT = (	SELECT TINHTRANGDH
									FROM DONHANG 
									WHERE MADH = @MADH)
	
	WAITFOR DELAY '0:0:05'
	IF (@TINHTRANGDH != 0)
	BEGIN
		PRINT N'BAN KHONG THE CAP NHAT TINH TRANG DON HANG NAY'
		ROLLBACK TRAN
		RETURN		
	END
	WAITFOR DELAY '0:0:05'
	BEGIN TRY
		UPDATE DONHANG
		SET MATX = @MATX, TINHTRANGDH = @TINHTRANG
		WHERE MADH = @MADH 
	END TRY
	BEGIN CATCH 
		DECLARE @ErrorMsg VARCHAR(2000)
		SELECT @ErrorMsg = N'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ErrorMsg, 16,1)
		ROLLBACK TRAN
		RETURN
	END CATCH

	PRINT 'CAP NHAT TINH TRANG DON HANG THANH CONG'
COMMIT TRAN