

CREATE PROCEDURE SP_XEMGIASP

@MASP varchar(10)
AS 
BEGIN TRANSACTION 
	BEGIN TRY
		IF NOT EXISTS (SELECT * FROM SANPHAM WHERE MASP = @MASP)
		BEGIN
			PRINT  @MASP + N' KHÔNG TỒN TẠI'
			ROLLBACK TRAN
			RETURN 1
		END
		SELECT * FROM SANPHAM WHERE MASP=@MASP;
			WAITFOR DELAY '00:00:05'

		SELECT * FROM SANPHAM WHERE MASP =@MASP;

		END TRY
			BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRANSACTION
RETURN 0


GO

CREATE PROCEDURE SP_CAPNHAPGIASP

@MASP varchar(10)
AS 
BEGIN TRANSACTION 
	BEGIN TRY
		IF NOT EXISTS (SELECT * FROM SANPHAM WHERE MASP = @MASP)
		BEGIN
			PRINT  @MASP + N' KHÔNG TỒN TẠI'
			ROLLBACK TRAN
			RETURN 1
		END
		UPDATE SANPHAM SET GIA = 5000 WHERE MASP =@MASP
		END TRY
			BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRANSACTION
RETURN 0




