/*
 *  Student's ID: 19127622
 *  Full name: Ngo Truong Tuyen
 *  Subject: Java Programming
 *  Assignment :
 *  Problem :
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zerotus
 */
public class DT_DangKyLapHopDong extends javax.swing.JFrame {
    Connection connection;
    /**
     * Creates new form ManagerList
     */
    public DT_DangKyLapHopDong() {
        initComponents();
    }
    public String getMaHD(){
        int count=0;
        connection= DBInfo.connect();
        String sql = "SELECT COUNT (MAHD) AS ROW_COUNT FROM HOPDONG";
        try {
            Statement s = connection.createStatement();
            ResultSet rs = s.executeQuery(sql);
            rs.next();
            count = rs.getInt("ROW_COUNT");
        } catch (SQLException e) {
            e.printStackTrace();
        }


        return "HD000"+(count+1);
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtTaxID = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtBranchAddress = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtRepresentativeName = new javax.swing.JTextField();
        txtBranchQuantity = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("HỆ THỐNG ĐẶT VÀ CHUYỂN HÀNG ONLINE");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1520, 90));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Quản lý nhân viên");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 654, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Đăng ký lập đợp đồng");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 570, 40));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnBack.setText("Quay lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel8.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, 210, 60));

        btnSignUp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSignUp.setText("Đăng ký");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        jPanel8.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 210, 60));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 700, 1520, 70));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Mã số thuế đối tác");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 190, 40));

        txtTaxID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel7.add(txtTaxID, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 260, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Địa chỉ chi nhánh");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 210, 40));

        txtBranchAddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel7.add(txtBranchAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 260, 40));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Người đại diện");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 140, 40));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Số chi nhánh đăng ký");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 230, 40));

        txtRepresentativeName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel7.add(txtRepresentativeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 260, 40));

        txtBranchQuantity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel7.add(txtBranchQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 260, 40));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 1130, 470));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 1520, 560));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 780));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        try {
            // TODO add your handling code here:
            connection =DBInfo.connect();
            String taxID = txtTaxID.getText();
            
            String RepresentativeName = txtRepresentativeName.getText();
            String BranchQuantity = txtBranchQuantity.getText();
            String BranchAddress = txtBranchAddress.getText();
            String sqlCheck = "SELECT * FROM DOITAC WHERE MAST ='"+taxID+"' AND NGUOIDAIDIEN=N'"+RepresentativeName+"' AND SOCN='"+BranchQuantity+"'";
        //    PreparedStatement ps = connection.prepareStatement(sqlCheck);
         //   ps.setString(1, taxID);
         //   ps.setString(2, RepresentativeName);
         //   ps.setString(3, BranchQuantity);
            
          //  
          Statement st = connection.createStatement();
          ResultSet rs = st.executeQuery(sqlCheck);
          if(rs.next()){             
              String ContractID = getMaHD();
              
              
              String PartnerID = rs.getString("MADT");
              
              //String taxID = rs.getString("MAST");
              String sqlInsert = "INSERT INTO HOPDONG"
                      + " (MAHD,MADT,MAST,NGUOIDAIDIEN,SOCHINHANHDK,DIACHICN,PHIKICHHOAT,TINHTRANGHD)"
                      + "VALUES(?,?,?,?,?,?,?,?) ";
              PreparedStatement ps2 = connection.prepareStatement(sqlInsert);
              ps2.setString(1, ContractID);
              ps2.setString(2, PartnerID);
              ps2.setString(3, taxID);
              ps2.setString(4, RepresentativeName);
              ps2.setString(5, BranchQuantity);
              ps2.setString(6, BranchAddress);
              ps2.setString(7, "1000000");
              ps2.setString(8, "0");
              ps2.executeUpdate();  
              JOptionPane.showMessageDialog(null, "Đăng ký lập hợp đồng thành công");
          }
          else{
              JOptionPane.showMessageDialog(null, "Không tìm thấy thông tin đối tác");
          }
        } catch (SQLException ex) {
            Logger.getLogger(DT_DangKyLapHopDong.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        DT_DashBoard1 DTDB = new DT_DashBoard1();
        dispose();
        DTDB.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DT_DangKyLapHopDong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DT_DangKyLapHopDong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DT_DangKyLapHopDong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DT_DangKyLapHopDong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DT_DangKyLapHopDong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField txtBranchAddress;
    private javax.swing.JTextField txtBranchQuantity;
    private javax.swing.JTextField txtRepresentativeName;
    private javax.swing.JTextField txtTaxID;
    // End of variables declaration//GEN-END:variables
}
