/*
 *  Student's ID: 19127622
 *  Full name: Ngo Truong Tuyen
 *  Subject: Java Programming
 *  Assignment :
 *  Problem :
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zerotus
 */

public class DT_QuanLySanPham extends javax.swing.JFrame {

    /**
     * Creates new form ManagerList
     */
    Connection connection;
    public DT_QuanLySanPham() {
        connection = DBInfo.connect();
        initComponents();
        table_load();
    }
    void table_load(){
        // Statement statement = null;
       // connection = DBInfo.connect();
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
       tableModel.setRowCount(0);
       tableModel.setColumnCount(0);
        try {
            String sql1 ="SELECT * FROM SANPHAM,CHINHANH_SANPHAM WHERE SANPHAM.MASP=CHINHANH_SANPHAM.MASP AND MADT='"+DangNhap.userID+"'";
            Statement statement = connection.createStatement();
            ResultSet rs1 = statement.executeQuery(sql1);

            while (rs1.next()) {
                String MASP = rs1.getString("MASP");
                String TENSP = rs1.getString("TENSP");
                String GIA = rs1.getString("GIA");
                String MaDT = rs1.getString("MADT");
                String MaCN= rs1.getString("MACN");
                String SL= rs1.getString("SOLUONGTON");
                String tData[] = { MASP, TENSP, GIA,MaDT,MaCN,SL};
                //      DefaultTableModel tableModel = (DefaultTableModel) table1.getModel();
                tableModel.setColumnIdentifiers(new Object[]{"Mã sản phẩm","Tên sản phẩm",
                        "Giá","Mã đối tác","Mã chi nhánh","Số lượng tồn"});
                tableModel.addRow(tData);
            }
           

        } catch (SQLException e) {
            e.printStackTrace();
        }

    }
    public boolean isExistPro(String ProID){
       // connection=DBInfo.connect();
        String sql_check="SELECT * FROM CHINHANH_SANPHAM WHERE MASP = '" + ProID + "' AND MADT = '"+DangNhap.userID+"'";
        Statement stmt = null;
        try {
            stmt = connection.createStatement();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        ResultSet rs = null;
        try {
            rs = stmt.executeQuery(sql_check);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,  e);
            e.printStackTrace();
        }
        try {
            if(rs.next()){
     
                return true;
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,  e);
            e.printStackTrace();
        }
        return false;
    }
    
    public boolean isExistProInOrder(String ProID){
       // connection=DBInfo.connect();
        String sql_check="SELECT * FROM CTDONHANG,DONHANG WHERE MASP = '" + ProID + "' AND MADT = '"+DangNhap.userID+"' "
                + "AND CTDONHANG.MADH = DONHANG.MADH";
        Statement stmt = null;
        try {
            stmt = connection.createStatement();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        ResultSet rs = null;
        try {
            rs = stmt.executeQuery(sql_check);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,  e);
            e.printStackTrace();
        }
        try {
            if(rs.next()){
     
                return true;
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,  e);
            e.printStackTrace();
        }
        return false;
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnSeeAll = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtProductID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        txtProductName = new javax.swing.JTextField();
        txtBranchID = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtSearchingProductID = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("HỆ THỐNG ĐẶT VÀ CHUYỂN HÀNG ONLINE");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1520, 90));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Quản lý nhân viên");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 654, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Quản lý sản phẩm");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 570, 40));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel8.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 210, 60));

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel8.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 210, 60));

        btnSeeAll.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSeeAll.setText("Xem tất cả");
        btnSeeAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeeAllActionPerformed(evt);
            }
        });
        jPanel8.add(btnSeeAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 210, 60));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnUpdate.setText("Cập nhập");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel8.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 210, 60));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnBack.setText("Quay lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel8.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 0, 210, 60));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 700, 1520, 70));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Mã sản phẩm");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 140, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Tên sản phẩm");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 140, 40));

        txtProductID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtProductID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductIDActionPerformed(evt);
            }
        });
        jPanel6.add(txtProductID, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 260, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Số lượng tồn");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 140, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Đơn giá");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 140, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Thêm sản phẩm");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 160, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Mã chi nhánh");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 140, 40));

        txtQuantity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });
        jPanel6.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 260, 40));

        txtProductName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductNameActionPerformed(evt);
            }
        });
        jPanel6.add(txtProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 260, 40));

        txtBranchID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtBranchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBranchIDActionPerformed(evt);
            }
        });
        jPanel6.add(txtBranchID, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 260, 40));

        txtPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });
        jPanel6.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 260, 40));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 590, 360));

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Mã sản phẩm");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 140, 40));

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSearch.setText("Tìm kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel7.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 150, 50));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Tìm kiếm sản phẩm");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 200, 40));

        txtSearchingProductID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel7.add(txtSearchingProductID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 260, 40));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 590, 150));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Mã đối tác", "Mã chi nhánh", "Đơn giá", "Số lượng tồn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 860, 510));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 880, 530));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 1520, 560));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 780));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
         DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
       tableModel.setRowCount(0);
       tableModel.setColumnCount(0);
        connection = DBInfo.connect();
        String ProID_Search = txtSearchingProductID.getText();
        if(isExistPro(ProID_Search)==false){
            JOptionPane.showMessageDialog(null,"Không tồn tại sản phẩm");
            return;
        }
        
        
        String sql = "SELECT * FROM SANPHAM,CHINHANH_SANPHAM WHERE SANPHAM.MASP=CHINHANH_SANPHAM.MASP AND SANPHAM.MASP = '"+ProID_Search+"'";
        try {
            Statement statement = connection.createStatement();
            ResultSet rs = statement.executeQuery(sql);
            while(rs.next()){
                String ProID = rs.getString("MASP");
                String ProName = rs.getString ("TENSP");
                String Price = rs.getString("GIA");
                String PartnerID = rs.getString ("MADT");
                String BrachID = rs.getString("MACN");
                String Quantity = rs.getString ("SOLUONGTON");
                String result = ProID +" "+ ProName+" "+Price+" "+PartnerID+" "+Quantity;
                System.out.println(result);
                String tdata[] = {ProID,ProName,Price,PartnerID,BrachID,Quantity};
                tableModel.setColumnIdentifiers(new Object[]{"Mã sản phẩm","Tên sản phẩm",
                        "Giá","Mã đối tác","Mã chi nhánh","Số lượng tồn"});
                tableModel.addRow(tdata);
            }
          //  String tdata[] = {ProID,ProName,PartnerID,BrachID,Price,Quantity};
           
        } catch (SQLException ex) {
            Logger.getLogger(DT_QuanLySanPham.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtSearchingProductID.setText("");
    }//GEN-LAST:event_btnSearchActionPerformed
   
           
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        connection =DBInfo.connect();
        String ProID = txtProductID.getText();
        if(isExistPro(ProID)==false){
            JOptionPane.showMessageDialog(null,"Không tồn tại sản phẩm");
            return;
        }
        if(isExistProInOrder(ProID)){
            JOptionPane.showMessageDialog(null,"Không thể xóa, sản phẩm đã tồn tại trong 1 đơn hàng nào đó");
            return;
        }
        String sql = "DELETE FROM SANPHAM WHERE MASP = ?";
                String sqlCNSP = "DELETE FROM CHINHANH_SANPHAM WHERE MASP= ?";
                try {
                    PreparedStatement psm = connection.prepareStatement(sql);
                     psm.setString(1,ProID);
                              
                    PreparedStatement psmCNSP = connection.prepareStatement(sqlCNSP);

                    psmCNSP.setString(1,ProID);
                    psmCNSP.executeUpdate();
                    psm.executeUpdate();
                    table_load();
                    JOptionPane.showMessageDialog(null,"Xóa thành công");
                   
                } catch (SQLException ex) {
                   
                    
                    ex.printStackTrace();
                    
                }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String ProID = txtProductID.getText();
        String ProName = txtProductName.getText();
        String Price = txtPrice.getText();
        String PartnerID = DangNhap.userID;
        String BrachID = txtBranchID.getText();
        String Quantity = txtQuantity.getText();
       // JOptionPane.showMessageDialog(null,ProID +" "+ ProName+" "+Price+" "+PartnerID+" "+Quantity);
        if(isExistPro(ProID)==true){
             JOptionPane.showMessageDialog(null,"Sản phẩm đã tồn tại");
             return;
         }
       if(ProName.length()==0||Price.length()==0||PartnerID.length() ==0||BrachID.length()==0||Quantity.length()==0){
           JOptionPane.showMessageDialog(null,"Không được để trống các dòng");
            return;
       }
            String sql = "INSERT INTO SANPHAM VALUES(?,?,?)";
            String sqlCNSP="INSERT INTO CHINHANH_SANPHAM VALUES(?,?,?,?)";
        try {
                    PreparedStatement preparedStatement = connection.prepareStatement(sql);
                    preparedStatement.setString(1,ProID);
                    preparedStatement.setString(2,ProName);
                    preparedStatement.setString(3, Price);
                    preparedStatement.executeUpdate();
                    PreparedStatement preparedStatement1 = connection.prepareStatement(sqlCNSP);
                    preparedStatement1.setString(1,PartnerID);
                    preparedStatement1.setString(2,BrachID);
                    preparedStatement1.setString(3,ProID);
                    preparedStatement1.setString(4,Quantity);
                    preparedStatement1.executeUpdate();
                    JOptionPane.showMessageDialog(null,"Thêm thành công");
                    table_load();
                    connection.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,ex);
                    ex.printStackTrace();
                }    
                txtBranchID.setText("");
                
                txtPrice.setText("");
                txtProductName.setText("");
                txtProductID.setText("");
                txtQuantity.setText("");
                
                
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String ProID = txtProductID.getText();
        String ProName = txtProductName.getText();
        String Price = txtPrice.getText();
        String PartnerID = DangNhap.userID;
        String BrachID = txtBranchID.getText();
        String Quantity = txtQuantity.getText();
        if(isExistPro(ProID)==false){
             JOptionPane.showMessageDialog(null,"Sản phẩm không tồn tại");
             return;
         }
        if(ProName.length()==0||Price.length()==0||PartnerID.length() ==0||BrachID.length()==0||Quantity.length()==0){
           JOptionPane.showMessageDialog(null,"Không được để trống các dòng");
            return;
       }
        String sql = "UPDATE SANPHAM SET TENSP=?,GIA=? WHERE MASP= ?";
        String sqlCNSP = "UPDATE CHINHANH_SANPHAM SET MADT=?,SOLUONGTON= ? WHERE MASP= ? AND MACN= ?";
        try {
                    PreparedStatement psm = connection.prepareStatement(sql);
                    PreparedStatement psmCNSP = connection.prepareStatement(sqlCNSP);
                    psm.setString(1,ProName);
                    psm.setString(2,Price);
                    psm.setString(3,ProID);

                    psmCNSP.setString(1,PartnerID);
                   
                    psmCNSP.setString(2,Quantity);
                    psmCNSP.setString(3,ProID);
                     psmCNSP.setString(4,BrachID);
                    psmCNSP.executeUpdate();
                    psm.executeUpdate();
                    JOptionPane.showMessageDialog(null,"Cập nhập thành công");
                    table_load();
                   
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,ex);
                    ex.printStackTrace();
                }
       // txtBranchID.setText("");
       // txtPartnerID.setText("");
       // txtPrice.setText("");
       // txtProductName.setText("");
       // txtProductID.setText("");
       // txtQuantity.setText("");
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSeeAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeeAllActionPerformed
        table_load();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeeAllActionPerformed

    private void txtProductIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductIDActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtProductIDActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        dispose();
        DT_DashBoard1 DT = new DT_DashBoard1();
        DT.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void txtProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductNameActionPerformed

    private void txtBranchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBranchIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBranchIDActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DT_QuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DT_QuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DT_QuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DT_QuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DT_QuanLySanPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSeeAll;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBranchID;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProductID;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSearchingProductID;
    // End of variables declaration//GEN-END:variables
}
