import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zerotus
 */
public class TXXuLyDonHang extends javax.swing.JFrame {
    String userID;
    String userType;
    String currentUser;
    
    Connection conn = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    /**
     * Creates new form TXXuLyDonHang
     */
    public TXXuLyDonHang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        txtGetPackage = new javax.swing.JButton();
        txtViewIncome = new javax.swing.JButton();
        txtReload = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableDonHang = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtArea = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDriverID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtReload1 = new javax.swing.JButton();
        txtThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtGetPackage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtGetPackage.setText("Xác nhận giao hàng");
        txtGetPackage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGetPackageActionPerformed(evt);
            }
        });
        jPanel8.add(txtGetPackage, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 280, 60));

        txtViewIncome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtViewIncome.setText("Xem thu nhập");
        txtViewIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViewIncomeActionPerformed(evt);
            }
        });
        jPanel8.add(txtViewIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, 280, 60));

        txtReload.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtReload.setText("Tải lại");
        txtReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReloadActionPerformed(evt);
            }
        });
        jPanel8.add(txtReload, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 280, 60));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 700, 1520, 70));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableDonHang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableDonHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã đơn hàng", "Mã đối tác", "Mã khách hàng", "Mã tài xế", "Tên đơn hàng", "Tình trạng", "Phí", "Địa chỉ giao", "Hình thức thanh toán"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableDonHang);

        jPanel5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1500, 440));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1520, 460));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Số điện thoại");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 130, -1));

        txtPhone.setEditable(false);
        txtPhone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        jPanel3.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 160, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Số điện thoại");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 130, -1));

        txtArea.setEditable(false);
        txtArea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaActionPerformed(evt);
            }
        });
        jPanel3.add(txtArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, 360, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Khu vực hoạt động");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 200, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Mã tài xế");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, -1));

        txtDriverID.setEditable(false);
        txtDriverID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDriverID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDriverIDActionPerformed(evt);
            }
        });
        jPanel3.add(txtDriverID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 160, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 1520, 550));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("HỆ THỐNG ĐẶT VÀ CHUYỂN HÀNG ONLINE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1520, 90));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel7.setText("Xử lý đơn hàng");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        txtReload1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtReload1.setText("Tải lại");
        txtReload1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReload1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtReload1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 280, 60));

        txtThoat.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtThoat.setText("Thoát");
        txtThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThoatActionPerformed(evt);
            }
        });
        jPanel1.add(txtThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 110, 140, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void loadData() {
        txtDriverID.setText(userID);
        int nums;
        
        try {
            conn = DBInfo.connect();
            pstmt = conn.prepareStatement("select * from TAIXE where MATX = ?");
            pstmt.setString(1, userID);
            rs = pstmt.executeQuery();
            String area = "";
            while (rs.next()) {
                txtPhone.setText(rs.getString("SDT"));
                area = new String(rs.getString("KHUVUCHD"));
                txtArea.setText(area);
            }

            //load data from QUANTRIVIEN table
            pstmt = conn.prepareStatement("select * from DONHANG where DIACHIGIAO = ?");
            pstmt.setString(1, area);
            rs = pstmt.executeQuery();
            
            rs = pstmt.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            
            //nums = stData.getColumnCount();
            nums = stData.getColumnCount();
            DefaultTableModel recordTable = (DefaultTableModel) tableDonHang.getModel();
            recordTable.setRowCount(0);
            while (rs.next()) {
                Vector columnData = new Vector();
                for (int i = 0; i < nums; i++) {
                    columnData.add(rs.getString("MADH"));
                    columnData.add(rs.getString("MADT"));
                    columnData.add(rs.getString("MAKH"));
                    columnData.add(rs.getString("MATX"));
                    columnData.add(rs.getString("TENDH"));
                    int type = Integer.parseInt(rs.getString("TINHTRANGDH"));
                    if (type == 0) {
                        columnData.add("CHỜ TÀI XẾ");
                    }
                    else {
                        columnData.add("TÀI XẾ ĐÃ LẤY HÀNG");
                    }
                    
                    columnData.add(Integer.parseInt(rs.getString("PHIVANCHUYEN")));
                    columnData.add(rs.getString("DIACHIGIAO"));
                    columnData.add(rs.getString("HINHTHUCTT")); 
                }
                
                recordTable.addRow(columnData);
            }

        } catch (SQLException ex) {
            Logger.getLogger(ThongTinQuanTriVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void txtViewIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViewIncomeActionPerformed
        TXTheoDoiThuNhap driver = new TXTheoDoiThuNhap();
        driver.userID = userID;
        driver.userType = userType;
        driver.currentUser = currentUser;
        
        this.hide();
        driver.loadData();
        driver.setVisible(true);
    }//GEN-LAST:event_txtViewIncomeActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaActionPerformed

    private void txtDriverIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDriverIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDriverIDActionPerformed

    private void txtGetPackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGetPackageActionPerformed
        DefaultTableModel recordTable = (DefaultTableModel)tableDonHang.getModel();
        int selectedRows = tableDonHang.getSelectedRow();
        String packageID = recordTable.getValueAt(selectedRows, 0).toString();
        packageID = packageID.replaceAll("\\s+", "");
        String driverID = recordTable.getValueAt(selectedRows, 3).toString();
        driverID = driverID.replaceAll("\\s+", "");
        if (driverID.equals("TX0000")) {
            try {
                conn = DBInfo.connect();
                pstmt = conn.prepareStatement("update DONHANG SET MATX = ?, TINHTRANGDH = 1 where MADH = ?");
                pstmt.setString(1, userID);
                pstmt.setString(2, packageID);
                pstmt.executeUpdate();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Có lỗi xảy ra, cập nhật không thành công!");
            }
            this.loadData();
            JOptionPane.showMessageDialog(null, "Tiếp nhận đơn hàng thành công!");  
        }
        else {
           JOptionPane.showMessageDialog(null, "Đơn hàng này đã có tài xế giao, vui lòng chọn đơn hàng khác!"); 
        }
    }//GEN-LAST:event_txtGetPackageActionPerformed

    private void txtThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThoatActionPerformed
        DangNhap login = new DangNhap();
        this.hide();
        login.setVisible(true);
    }//GEN-LAST:event_txtThoatActionPerformed

    private void txtReload1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReload1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReload1ActionPerformed

    private void txtReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReloadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReloadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TXXuLyDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TXXuLyDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TXXuLyDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TXXuLyDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TXXuLyDonHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tableDonHang;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtDriverID;
    private javax.swing.JButton txtGetPackage;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JButton txtReload;
    private javax.swing.JButton txtReload1;
    private javax.swing.JButton txtThoat;
    private javax.swing.JButton txtViewIncome;
    // End of variables declaration//GEN-END:variables
}
