
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JOptionPane;


/**
 *
 * @author zerotus
 */
public class UI_Demo_DirtyRead_T1 extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    /**
     * Creates new form UI_Demo_DirtyRead_T1
     */
    public UI_Demo_DirtyRead_T1() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableAccount1 = new javax.swing.JTable();
        btnReset = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnRunErrror = new javax.swing.JButton();
        btnFixError = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableAccount2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtAccountID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("TÌNH HUỐNG TRANH CHẤP - DIRTY READ");
        jPanel10.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1520, 80));

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableAccount1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableAccount1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã tài khoản", "Mật khẩu", "Loại người dùng", "Tình trạng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableAccount1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAccount1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tableAccount1);

        jPanel16.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 800, 250));

        jPanel13.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 820, 270));

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnReset.setText("Khôi phục");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel13.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 450, 170, 60));

        btnView.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnView.setText("Xem");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        jPanel13.add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 550, 170, 60));

        btnRunErrror.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnRunErrror.setText("Chạy lỗi");
        btnRunErrror.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunErrrorActionPerformed(evt);
            }
        });
        jPanel13.add(btnRunErrror, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 450, 170, 60));

        btnFixError.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnFixError.setText("Sửa lỗi");
        btnFixError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFixErrorActionPerformed(evt);
            }
        });
        jPanel13.add(btnFixError, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 550, 170, 60));

        jPanel17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableAccount2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableAccount2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã tài khoản", "Mật khẩu", "Loại người dùng", "Tình trạng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableAccount2);

        jPanel17.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 800, 250));

        jPanel13.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 820, 270));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Sau");
        jPanel13.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 350, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Cập nhật tài khoản tài xế");
        jPanel13.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 240, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Trước");
        jPanel13.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 380, -1));

        txtStatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel13.add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 270, 310, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Mã tài khoản");
        jPanel13.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 80, 140, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Mật khẩu");
        jPanel13.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 140, 140, 40));

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel13.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 140, 310, 40));

        jLabel4.setText("*Bỏ trống nếu không muốn đổi mật khẩu");
        jPanel13.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Loại người dùng");
        jPanel13.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 210, 170, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("3:  Tài xế");
        jPanel13.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 210, 140, 40));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Tình trạng");
        jPanel13.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 270, 140, 40));

        txtAccountID.setEditable(false);
        txtAccountID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel13.add(txtAccountID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 80, 310, 40));

        jPanel9.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1520, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 1539, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private int getStatus(String status) {
        return Integer.parseInt(status.substring(0, 1));
    }
    
    private void loadDataToTable2() {
        int nums;
        try{
            conn = DBInfo.connect();
            pstmt = conn.prepareStatement("select * from TAIKHOAN");

            rs = pstmt.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();

            nums = stData.getColumnCount();

            DefaultTableModel recordTable2 = (DefaultTableModel) tableAccount2.getModel();
            recordTable2.setRowCount(0);
            
            while (rs.next()) {
                boolean isDriver = false;
                Vector columnData = new Vector();
                String typeString;
                for (int i = 1; i <= nums; i++) {
                    int type = rs.getInt("LOAIND");
                    if (type == 3) {
                        isDriver = true;
                        
                        columnData.add(rs.getString("MATK"));
                        columnData.add(rs.getString("MATKHAU"));
                        columnData.add("Tài xế");
                        int status = rs.getInt("TINHTRANG");
                        columnData.add(status);
                        String statusString;
                        if (status == 0) {
                            statusString = new String ("Bị khóa");
                        }
                        else {
                            statusString = new String ("Bình thường");
                        }
                    }
                }
                if (isDriver) {
                    recordTable2.addRow(columnData);
                }
                
            }

        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Không thể xem thông tin");
        }
    }
    
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        try {
            conn = DBInfo.connect();
            pstmt = conn.prepareStatement("update TAIKHOAN set MATKHAU = 12345, TINHTRANG = 1");
            pstmt.executeUpdate();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Khôi phục thất bại");
        }

        DefaultTableModel RecordTable1 = (DefaultTableModel) tableAccount1.getModel();
        RecordTable1.setRowCount(0);

        DefaultTableModel RecordTable2 = (DefaultTableModel) tableAccount2.getModel();
        RecordTable2.setRowCount(0);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        int nums;
        try{
            conn = DBInfo.connect();
            pstmt = conn.prepareStatement("select * from TAIKHOAN");

            rs = pstmt.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();

            nums = stData.getColumnCount();

            DefaultTableModel recordTable = (DefaultTableModel) tableAccount1.getModel();
            recordTable.setRowCount(0);
            
            while (rs.next()) {
                boolean isDriver = false;
                Vector columnData = new Vector();
                String typeString;
                for (int i = 1; i <= nums; i++) {
                    int type = rs.getInt("LOAIND");
                    if (type == 3) {
                        isDriver = true;
                        columnData.add(rs.getString("MATK"));
                        columnData.add(rs.getString("MATKHAU"));
                        columnData.add("Tài xế");
                        columnData.add(rs.getInt("TINHTRANG"));
                    }
                }
                if (isDriver) {
                    recordTable.addRow(columnData);
                }
                
            }

        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Không thể xem thông tin");
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnRunErrrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunErrrorActionPerformed
        DefaultTableModel recordTable = (DefaultTableModel)tableAccount1.getModel();
        int selectedRows = tableAccount1.getSelectedRow();
        String userID = recordTable.getValueAt(selectedRows, 0).toString();
        userID = userID.replaceAll("\\s+", "");
        String pwd = recordTable.getValueAt(selectedRows, 1).toString();
        pwd = pwd.replaceAll("\\s+", "");
        
        
        try {
            conn = DBInfo.connect();
            pstmt = conn.prepareStatement("EXEC SP_CAPNHATTK ?, ?, ?");
            pstmt.setString(1, txtAccountID.getText());
            String password = new String(txtPassword.getPassword());
            if (password.length() != 0) {
                pstmt.setString(2, password);
            } else {
                pstmt.setString(2, pwd);
            }
            pstmt.setString(3, txtStatus.getText());
            pstmt.executeUpdate();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Có lỗi xảy ra, cập nhật không thành công!");
        }

        this.loadDataToTable2();
    }//GEN-LAST:event_btnRunErrrorActionPerformed

    private void btnFixErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFixErrorActionPerformed
        DefaultTableModel recordTable = (DefaultTableModel)tableAccount1.getModel();
        int selectedRows = tableAccount1.getSelectedRow();
        String userID = recordTable.getValueAt(selectedRows, 0).toString();
        userID = userID.replaceAll("\\s+", "");
        String pwd = recordTable.getValueAt(selectedRows, 1).toString();
        pwd = pwd.replaceAll("\\s+", "");
        
        
        try {
            conn = DBInfo.connect();
            pstmt = conn.prepareStatement("EXEC SP_CAPNHATTK_FIX ?, ?, ?");
            pstmt.setString(1, txtAccountID.getText());
            String password = new String(txtPassword.getPassword());
            if (password.length() != 0) {
                pstmt.setString(2, password);
            } else {
                pstmt.setString(2, pwd);
            }
            pstmt.setString(3, txtStatus.getText());
            pstmt.executeUpdate();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Có lỗi xảy ra, cập nhật không thành công!");
        }

        this.loadDataToTable2();
    }//GEN-LAST:event_btnFixErrorActionPerformed

    private void tableAccount1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAccount1MouseClicked
        DefaultTableModel recordTable = (DefaultTableModel)tableAccount1.getModel();
        int selectedRows = tableAccount1.getSelectedRow();
        String userID = recordTable.getValueAt(selectedRows, 0).toString();
        userID = userID.replaceAll("\\s+", "");
        String typeString = recordTable.getValueAt(selectedRows, 3).toString();
        
        
        txtAccountID.setText(userID);
        txtStatus.setText(typeString);
        
    }//GEN-LAST:event_tableAccount1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_Demo_DirtyRead_T1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_Demo_DirtyRead_T1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_Demo_DirtyRead_T1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_Demo_DirtyRead_T1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_Demo_DirtyRead_T1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFixError;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnRunErrror;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tableAccount1;
    private javax.swing.JTable tableAccount2;
    private javax.swing.JTextField txtAccountID;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
}
