
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author zerotus
 */
public class UI_Demo_DirtyRead_T2 extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    /**
     * Creates new form UI_Demo_DirtyRead_T2
     */
    public UI_Demo_DirtyRead_T2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableAccount1 = new javax.swing.JTable();
        btnReset = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnRunErrror = new javax.swing.JButton();
        btnFixError = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAccountID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("TÌNH HUỐNG TRANH CHẤP - DIRTY READ");
        jPanel10.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1520, 80));

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableAccount1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableAccount1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã tài khoản", "Mật khẩu", "Loại người dùng", "Tình trạng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableAccount1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAccount1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tableAccount1);

        jPanel16.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 800, 510));

        jPanel13.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 820, 540));

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnReset.setText("Khôi phục");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel13.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 400, 170, 60));

        btnView.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnView.setText("Xem");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        jPanel13.add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 550, 170, 60));

        btnRunErrror.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnRunErrror.setText("Chạy lỗi");
        btnRunErrror.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunErrrorActionPerformed(evt);
            }
        });
        jPanel13.add(btnRunErrror, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 400, 170, 60));

        btnFixError.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnFixError.setText("Sửa lỗi");
        btnFixError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFixErrorActionPerformed(evt);
            }
        });
        jPanel13.add(btnFixError, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 550, 170, 60));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Cập nhật tài khoản tài xế");
        jPanel13.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 240, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Trước");
        jPanel13.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 380, -1));

        txtAccountID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel13.add(txtAccountID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 130, 310, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Mã tài khoản");
        jPanel13.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 130, 140, 40));

        jPanel9.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1520, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 1539, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tableAccount1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAccount1MouseClicked

    }//GEN-LAST:event_tableAccount1MouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        DefaultTableModel RecordTable1 = (DefaultTableModel) tableAccount1.getModel();
        RecordTable1.setRowCount(0);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        int nums;
        try{
            conn = DBInfo.connect();
            pstmt = conn.prepareStatement("select * from TAIKHOAN where MATK = ?");
            pstmt.setString(1, txtAccountID.getText());
            rs = pstmt.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();

            nums = stData.getColumnCount();

            DefaultTableModel recordTable = (DefaultTableModel) tableAccount1.getModel();
            recordTable.setRowCount(0);

            while (rs.next()) {
                Vector columnData = new Vector();
                String typeString;
                for (int i = 1; i <= nums; i++) {
                    int type = rs.getInt("LOAIND");
                    if (type == 3) {
                        columnData.add(rs.getString("MATK"));
                        columnData.add(rs.getString("MATKHAU"));
                        columnData.add("Tài xế");
                        columnData.add(rs.getInt("TINHTRANG"));
                    }
                }
                recordTable.addRow(columnData);


            }

        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Không thể xem thông tin");
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnRunErrrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunErrrorActionPerformed
        int nums;
        try {
            conn = DBInfo.connect();
            pstmt = conn.prepareStatement("EXEC SP_XEMTK ?");
            pstmt.setString(1, txtAccountID.getText());
            rs = pstmt.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();

            nums = stData.getColumnCount();

            DefaultTableModel recordTable = (DefaultTableModel) tableAccount1.getModel();
            recordTable.setRowCount(0);
            
            while(rs.next()) {
                boolean isDriver = false;
                Vector columnData = new Vector();
                String typeString;
                for (int i = 1; i <= nums; i++) {
                    int type = rs.getInt("LOAIND");
                    if (type == 3) {
                        isDriver = true;
                        columnData.add(rs.getString("MATK"));
                        columnData.add(rs.getString("MATKHAU"));
                        columnData.add("Tài xế");
                        columnData.add(rs.getInt("TINHTRANG"));
                    }
                }
                
                recordTable.addRow(columnData);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Có lỗi xảy ra, cập nhật không thành công!");
        }
        
    }//GEN-LAST:event_btnRunErrrorActionPerformed

    private void btnFixErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFixErrorActionPerformed
        int nums;
        try {
            conn = DBInfo.connect();
            pstmt = conn.prepareStatement("EXEC SP_XEMTK_FIX ?");
            pstmt.setString(1, txtAccountID.getText());
            rs = pstmt.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();

            nums = stData.getColumnCount();

            DefaultTableModel recordTable = (DefaultTableModel) tableAccount1.getModel();
            recordTable.setRowCount(0);
            
            while(rs.next()) {
                boolean isDriver = false;
                Vector columnData = new Vector();
                String typeString;
                for (int i = 1; i <= nums; i++) {
                    int type = rs.getInt("LOAIND");
                    if (type == 3) {
                        isDriver = true;
                        columnData.add(rs.getString("MATK"));
                        columnData.add(rs.getString("MATKHAU"));
                        columnData.add("Tài xế");
                        columnData.add(rs.getInt("TINHTRANG"));
                    }
                }
                
                recordTable.addRow(columnData);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Có lỗi xảy ra, cập nhật không thành công!");
        }
    }//GEN-LAST:event_btnFixErrorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_Demo_DirtyRead_T2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_Demo_DirtyRead_T2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_Demo_DirtyRead_T2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_Demo_DirtyRead_T2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_Demo_DirtyRead_T2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFixError;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnRunErrror;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tableAccount1;
    private javax.swing.JTextField txtAccountID;
    // End of variables declaration//GEN-END:variables
}
