--XY LY DON HANG

--DROP PROC SP_XULYDH
				
CREATE 
--ALTER
PROC SP_XULYDH
	@MATX CHAR(10),
	@MADH CHAR(10),
	@TINHTRANG INT

AS
SET TRAN ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRAN
	DECLARE @TINHTRANGDH INT = (	SELECT TINHTRANGDH
											FROM DONHANG WITH(UPDLOCK)
											WHERE MADH = @MADH)
	
	IF (@TINHTRANGDH = 0)
	BEGIN
		SET @TINHTRANGDH = 1;
	END
		ELSE
	BEGIN
		PRINT N'DON HANG DA CO TAI XE GIAO'
		ROLLBACK TRAN
		RETURN
	END
	WAITFOR DELAY '0:0:05'
	BEGIN TRY
		UPDATE DONHANG
		SET MATX = @MATX, TINHTRANGDH = @TINHTRANG
		WHERE MADH = @MADH 
	END TRY
	BEGIN CATCH 
		DECLARE @ErrorMsg VARCHAR(2000)
		SELECT @ErrorMsg = N'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ErrorMsg, 16,1)
		ROLLBACK TRAN
		RETURN
	END CATCH

	PRINT 'CAP NHAT TINH TRANG DON HANG THANH CONG'
COMMIT TRAN